### ISSUE TITLE
Drop the per-connection packet buffer to improve memory usage

### ISSUE THREAD

**Issue by bengal** [nettools/n-dhcp4#26]
Each connection object includes a 64KiB buffer used for receiving packets:

https://github.com/nettools/n-dhcp4/blob/v1/src/n-dhcp4-private.h#L308

In NetworkManager, this buffer in responsible for 30% of the memory usage when there are many connections active. For example, with 500 connections, NM consumes ~100MiB of which ~30MiB are used by the packet buffer.

We should consider allocating the buffer only when needed. Using `recv(..., MSG_PEEK|MSG_TRUNC)` it's possible to get the incoming packet length and only allocate the right space.

**Comment by thom311** [comment]
`recv(..., MSG_PEEK|MSG_TRUNC)` requires to always make two syscalls, while also complicating the code.

Maybe we could use a thread-local global buffer instead?

**Comment by bengal** [comment]
Yes, a thread-local global buffer would work as well.
