### ISSUE TITLE
Update README with status of master branch

### ISSUE THREAD

**Issue by lsem** [nettools/n-dhcp4#28]
Is that possible to write whether master is ready to use or one should wait for release?
I would like to use the library and not sure which version to take. I tend to use releases, but it seems like there is no plans for release and may be using master is fine.

**Comment by thom311** [comment]
master is as ready as it ever will be and no more work is currently planned. Which does not mean, there are no (unknown) bugs or missing features.

It's used by NetworkManager, as the default DHCP implementation. We use it via `git-subtree`, but `git-submodule` would also work. We link statically against it. For that, we also "fork" the other c-tools dependencies. See [here](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/tree/edc37b3adf7d39057e7f06aa4ab736b38f7c8162/src). The code using the library is [here](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/blob/edc37b3adf7d39057e7f06aa4ab736b38f7c8162/src/core/dhcp/nm-dhcp-nettools.c).

I guess, there could also be a "release", and package the library as shared library. But that is currently not planned nor worked on. Using the code from git works well for NetworkManager (the currently only user).

You would use the latest `master` version from here... but there is no promise that the latest master wouldn't be broken (in practice, it seems to be stable). So please do some testing when upgrading and report issues.


Patch for upgrading README is welcome. It's not clear to me what should be said there.

**Comment by lsem** [comment]
Thanks for clarification @thom311.
