### ISSUE TITLE
IP header flags of DHCP discover packet

### ISSUE THREAD

**Issue by lsem** [nettools/n-dhcp4#37]
We have found a case when DISCOVER packet gets unanswered in a setup where one wifi router connected to the other wifi router. On devices with other DHCP client libraries everything is fine but with n-dhcp4 does work for some reason. Working libraries do not have _don't fragment_ flag and don't have tos IPTOS_CLASS_CS6.

I'm trying to find out what is correct and what will I loose if I don't use these flags. My understanding is that fragmentation should not be an issue taking into account that DHCP packet size is ~380 bytes while MTU us ~1500. I also cannot find information whether tos flags can make packets get dropped.

Please let me know If you know something about it or can direct me to where I can read about this.

**Comment by thom311** [comment]
I don't know, but it may be helpful to compare what systemd's DHCP client does ([here](https://github.com/systemd/systemd/tree/0ea720ca7ea03a3dbf21a5d152e294b9a293dc3d/src/libsystemd-network)).
Maybe they handle it differently, and maybe there is a related report about the reasons.

**Comment by lsem** [comment]
Thanks for answering
